import mutate

dna = 'actgatcgatcgatcgtcagctactgcatcgatcacgtgacgtatcatcgcatgctacgtagctacgtacgtacgactcgatgcatcgactgatgctacgtagctagctgatcgatcagtacgtacgtagctagctgcagcatcgatgcatagtcgatcgcatgcatgcatagtcgactacgtacgtagctgactgactgactgactacgatcgactgactacgggtgactaaaaaaaaacacacaccccacacacacacacacatactactatcactacgactcgatgagagaagtgaactacgagtcacagatgcatacagatgatgatagatagctagcatgatagcatgcagaagaactgatatctacacgtacgtactgactgacgtactgactgactgactgactgacgtacgtacgtactgacgtactgacgtacgtacgtactgactgacgtacgtacgtacgtacgtactactgacgtacgtacactgacgtacgtacgtactactacacgtactgactacgtacgtacgtacgtactcatctgactgactgactcgtactactacgtactactacgtactgactgactactgactgactgatcatagtatggcgcgcgcgcgacgtacgtcagtcagctgtcagctgtacgatgctgctagcagtcagactgactacgtacgtcagatgatgatgctagccatgctagtacgatgactgactacgatcg'
alpha = 0.3
time = 10

def test_mutate(threads):
    return mutate.mutate(alpha, time, dna, threads)